### ISSUE TITLE
Dummy login is not appearing

### ISSUE THREAD

**Issue by docterd** [mirego/accent#124]
Hey, I just pulled up the Docker Container with following environment parameters. 

```
DUMMY_LOGIN_ENABLED=1
DATABASE_URL=postgresql://accent:accent@localhost/accent

```
Unfortunately I'm not able to progress on the frontend. Did I miss something?
<img width="696" alt="Screenshot 2019-10-14 at 15 32 58" src="https://user-images.githubusercontent.com/199578/66756452-57fbba00-ee9a-11e9-975e-227c13b0f755.png">

**Comment by ro-kue** [comment]
Same issue but with github client id and secret.

**Comment by 9KwHCUDP** [comment]
This problem occurs with SSL. You need to set API_HOST to `https://domain.tld`.

**Comment by docterd** [comment]
Thanks. That seems to make the login appear. Unfortunately after entering a email I'm not still not able to progress. I get redirected to the same screen. I can see in the Database, that a user and a token has been created.

**Comment by 9KwHCUDP** [comment]
Try setting `WEBAPP_URL` to the same value.

**Comment by docterd** [comment]
Both are set to the right URL.

**Comment by 9KwHCUDP** [comment]
Can you enable persistent logs in browser, and post them here?

**Comment by docterd** [comment]
Okay I found the issue. The last problem happened duo my HTTP Basic auth protection. Anything I can do to make it running with it?

**Comment by 9KwHCUDP** [comment]
You'll have to edit the authorization header name to work with basic auth.
