### ISSUE TITLE
Demo website is not working

### ISSUE THREAD

**Issue by charlot567** [mirego/accent#129]
Hey,

Just to advise you that the demo website is not working.
http://demo.accent.reviews/

![2019-11-26 at 4 53 PM](https://user-images.githubusercontent.com/1634975/69675748-57e00400-106d-11ea-848b-4a8994f9f106.png)

Thanks !

**Comment by simonprev** [comment]
Thank you for the report, since the demo runs on a free tier Heroku dyno, sometimes restarting the app takes too long and the process crashes 😢
