### ISSUE TITLE
Deploying to Heroku fails

### ISSUE THREAD

**Issue by machty** [mirego/accent#131]
I've tried to use the Heroku button a few times now and it keeps on failing "due to a release phase command in release v6"

There's no further information it provides, and since the app self-deletes after a failed deploy, there's no way for me to see what actually broke.

![image](https://user-images.githubusercontent.com/81818/70500890-9c968100-1aea-11ea-897e-367fac8a68b4.png)

Any ideas?

**Comment by machty** [comment]
I was able to get things deployed manually (setting up the app myself, selecting buildpacks, etc) after following the instructions on this very helpful comment: https://github.com/mirego/accent/issues/112#issuecomment-537626341

**Comment by simonprev** [comment]
The last few commits on `master` fix issues regarding Heroku Deploy button 🎉 
It was a missing line in the config `prod` https://github.com/mirego/accent/commit/6be6a64a1aba3e4c12483d4fcda88a9d54bb81d8 … We never saw it in production because we use `mix release`
