### ISSUE TITLE
Accent seems to ignore FORCE_SSL, WEBAPP_URL, et al

### ISSUE THREAD

**Issue by riverar** [mirego/accent#149]
Repro:
```
docker run -it -e DATABASE_URL=postgresql://user:pass@host/accent -e DUMMY_LOGIN_ENABLED=1 -e WEBAPP_URL=https://foo.com -e FORCE_SSL=1 -e MIX_ENV=prod -p 443:4000 mirego/accent
```

Results in:
```
Running migrations for accent…
07:23:05.822 [info] == Running 20191217180708 Accent.Repo.Migrations.AddForeignKeyIndexForOperations.change/0 forward
07:23:05.826 [info] create index operations_rollbacked_operation_id_index
Running seed script for accent…
07:23:18.745 [info] Running Accent.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
07:23:18.745 [info] Access Accent.Endpoint at http://localhost:4000
```

Expected to see an https endpoint and/or `WEBAPP_URL` value in the logs.

**Comment by remi** [comment]
Hi @riverar,

> Expected to see an https endpoint

Phoenix will never run an `https` endpoint per se, it always run an `http` endpoint. [What `FORCE_SSL` does](https://github.com/mirego/accent/blob/c7ce021273483f441de8e4bfbd2ef1828fe6a1ba/lib/accent/endpoint.ex#L39-L47) is ensure that all requests made to it are made through an SSL connection (and otherwise force a redirect to one).

See [`Plug.SSL`](https://hexdocs.pm/plug/Plug.SSL.html) for more information:

> If the scheme of a request is https, it'll add a strict-transport-security header to enable HTTP Strict Transport Security by default.
> 
> Otherwise, the request will be redirected to a corresponding location with the https scheme by setting the location header of the response. The status code will be 301 if the method of conn is GET or HEAD, or 307 in other situations.

**Comment by riverar** [comment]
Thanks @remi, what would a user utilizing this feature redirect to normally, if Accent doesn't support it?

**Comment by remi** [comment]
For example, if you deploy Accent on Heroku (on an app named `my-accent-app`), it will be available on both these URLs:

* http://my-accent-app.herokuapp.com
* https://my-accent-app.herokuapp.com

Heroku takes care of both the HTTP and HTTPS traffic and routes it to the Accent container listening on port 4000.

### Without `FORCE_SSL`

```bash
$ curl -sI -XGET http://my-accent-app.herokuapp.com
HTTP/2 200

$ curl -sI -XGET https://my-accent-app.herokuapp.com
HTTP/2 200
```

### With `FORCE_SSL`

```bash
$ curl -sI -XGET http://my-accent-app.herokuapp.com
HTTP/2 301
Location: https://my-accent-app.herokuapp.com

$ curl -sI -XGET https://my-accent-app.herokuapp.com
HTTP/2 200
```

Hope that clears things out!

**Comment by riverar** [comment]
Got it, thanks!
