### ISSUE TITLE
Wrong base URL in invitation email

### ISSUE THREAD

**Issue by remi** [mirego/accent#150]
We have Accent deployed on `https://app.accent.reviews` but when a user adds another one to a project, the logo is sourced from `http://localhost`.

All other links have working `https://app.accent.reviews` URLs.

<img width="1387" alt="" src="https://user-images.githubusercontent.com/11348/74162069-0cf67700-4bee-11ea-93e9-8387b76de489.png">

**Comment by remi** [comment]
@simonprev I don’t see any commit referencing #150 — was this fixed?

**Comment by simonprev** [comment]
Sneaky fix inside this commit: https://github.com/mirego/accent/commit/b3d89974322ae8dedd9c729d8444fa754d0cbb42
