### ISSUE TITLE
Error when imports android strings with html code

### ISSUE THREAD

**Issue by jValinho** [mirego/accent#154]

**Comment by jValinho** [comment]
We need to add new strings with html code "/b>" to apply bold word.
To include this html parameter in the string, we need to indicate <"![CDATA[html source code]]>

The sample could be this:
![image](https://user-images.githubusercontent.com/59615345/78151195-9ed57000-7438-11ea-8f93-fb1a8104e35c.png)

The problem is when we import the file to accent in android.xml format, it doesn´t recognize "![CDATA" and "/b>" 
I think it is because it doesn´t identify html code

Thanks
Regards

**Comment by simonprev** [comment]
This is related to this issue: https://github.com/mirego/accent/issues/37

I will do the follow up there instead 👍
