### ISSUE TITLE
Github & Discord Documentation

### ISSUE THREAD

**Issue by masonhensley** [mirego/accent#155]
https://www.accent.reviews/guides/service-integrations.html

The doc link above only lists Slack, however, the demo (screenshot below) seems to show support for Discord & Github. Should Discord and Github be included in the marketing/documentation?

![image](https://user-images.githubusercontent.com/534165/78272601-574ff200-74d3-11ea-9480-f8120e162f5b.png)

Cool project by the way, planning to add y'all to an open source project listing I'm working on 😎

**Comment by ad-m** [comment]
Before valid documentation will be prepared you can read commit message & pull requests which introduce GitHub integration:
https://github.com/mirego/accent/commit/e1b1b106c6a7fb2ff0a9d872d25f74c7a722dbcc
https://github.com/mirego/accent/commit/b314d0d12e92cd1b56d6b1da593e7b5701cd27f4
https://github.com/mirego/accent/pull/85

**Comment by simonprev** [comment]
Now available in the guides: https://www.accent.reviews/guides/service-integrations.html#github

😄
