### ISSUE TITLE
The "Add collaborator" button is always disabled

### ISSUE THREAD

**Issue by dbil25** [mirego/accent#162]
After deploying an instance on Heroku, everything seems to works fine except the `Add collaborator` button is always disabled.
![image](https://user-images.githubusercontent.com/7504247/79255083-b4dd2a80-7e53-11ea-8cbb-97e7854ad63c.png)

**Comment by simonprev** [comment]
Oh the two-way binding on input to update the button was removed recently on `master`… The next version will fix this, stay tuned for the next tagged version.

Do you have the option to use another branch to deploy on Heroku?

**Comment by dbil25** [comment]
yeah! we'll try that. Thanks for the info!

**Comment by dbil25** [comment]
Thanks! :clap:
