### ISSUE TITLE
User accounts are in an invalid state [JS artifacts]

### ISSUE THREAD

**Issue by KevinColemanInc** [mirego/accent#164]
I just deployed the project to Heroku via "Deploy with Heroku". Logging in and viewing ownership information shows this JS artifact.

In `https://website.com/app/projects/{..}/edit/collaborators` in Chrome on OSX:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/2381771/80289571-132bc800-86f4-11ea-88bb-8ef9b1826249.png">

When I try to login in Firefox by hitting the root domain:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/2381771/80289592-479f8400-86f4-11ea-8012-de38c7cb13bd.png">

My ENV config settings in heroku was:

DUMMY_LOGIN_ENABLED: false

**Comment by KevinColemanInc** [comment]
Might be related to https://github.com/mirego/accent/issues/162

**Comment by simonprev** [comment]
Yes it is now fixed in master. The main problem is that the _Heroku deploy button_ deploys the master branch and not a stable release 😢 I will look into using "container stack" for the Heroku deploy button.

**Comment by KevinColemanInc** [comment]
@simonprev 

https://devcenter.heroku.com/articles/heroku-button#adding-the-heroku-button

It seems like the button should of been working if the referrer was correctly passed.

In the docs, it seems you can give it a branch name. Maybe you could have a `releases` branch that only how stable releases?
