### ISSUE TITLE
RESTRICTED_DOMAIN is not related to CORS or CSP

### ISSUE THREAD

**Issue by KevinColemanInc** [mirego/accent#166]
The ENV variable sounds like its for adding CORS or CSP protections, but grepping through the source code, it really means only allow emails from this domain.

Could you update the documentation to be more clear?

**Comment by simonprev** [comment]
The description is _If specified, only authenticated users from this domain name will be able to create new projects._ Do you think this is enough?

**Comment by KevinColemanInc** [comment]
> from this domain name
IMHO, "this domain" sounds like the domain of accent app, not the domain of the user's email.

What about either renaming the ENV variable to "RESTRICTED_EMAIL_DOMAIN" or updating the definition:
```
If specified, only authenticated users with this domain name in their email will be able to create new projects.
```

Even better, why even let them "login" at all? why not reject them on sign-in?

**Comment by simonprev** [comment]
I agree, the name of the variable is misleading since it only affects which users can create projects.

We use this restriction to invite collaborator from other domains in our Accent instance. We use it to collaborate with our client which do not have a `@mirego.com` email.

**Comment by simonprev** [comment]
I renamed the config to `RESTRICTED_PROJECT_CREATOR_EMAIL_DOMAIN` in the next version. The old name will still work (to not break existing installation) but the new name will be the one in the documentation 👍
