### ISSUE TITLE
Document queries only return 30 documents

### ISSUE THREAD

**Issue by dbil25** [mirego/accent#167]
### 1. cannot list more than 30 documents
having a project with > 30 documents, the command 
```
accent stats
```
will only list 30 documents.

### 2. cannot add translations for more than 30 documents
Additionnaly, when doing the command
```
accent sync --add-translations
```
all master language files are pushed, but only 30 translations are synced. (presumably because the server only returns 30 paths)

**Comment by simonprev** [comment]
I bump the page size to 1000 in the latest [accent-cli](https://www.npmjs.com/package/accent-cli) version. You will also need the latest version of the API that accept the `pageSize` param in GraphQL.

Thank you for the report!
