### ISSUE TITLE
Semantic versioning for version

### ISSUE THREAD

**Issue by ad-m** [mirego/accent#171]
Hi,

We are at the stage of choosing CAT software for our organization. In our organization we have a distributed system working in the architecture of microservices.

The main problem we see is the translation of the results of asynchronous operations (https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#13-long-running-operations). We have planned that in this case the scheduler (subsystem with information about all operations) will perform translations, and worker (subsystem performing operations) will only provide template code and template parameters. Thanks to this, we will not store translated messages permanently, so we can translate them into the language of the user who checks the status of the operation.

In this case, we must have synchronization of translations in the two subsystems, which have a completely separate life cycle and are generally loosely connected.

We're going to create a new project for the shared part and use tagging to facilitate synchronization. However, creating a new version tag and updating the system configuration is quite demanding. Instead of this, we would prefer to update gradually between versions that do not contain "breaking-changes" when system reload.

Are there plans to allow downloading of the version by indicating the partial version tag (or tag wildcard), e.g. in the presence of "1.0.0", "1.0.1" tags and requests to download "1.0" to deliver "1.0.1"? If not, what is the other recommended way to resolve this use case?

Greetings,

**Comment by simonprev** [comment]
That would be a simple feature to add! I don’t think there is a workaround right now. I will add the enhancement tag to work on it sometime in the future
