### ISSUE TITLE
Update Docker Hub image "mirego/accent"

### ISSUE THREAD

**Issue by ad-m** [mirego/accent#174]
Dear Sir or Madam,

I noticed that on GitHub we have the "1.5.0" release released 6 days ago. Meanwhile, the Docker Hub tag "latest" comes from over a month ago and is compatible with the version "1.4.5".

What is necessary to publish the current version on the Docker Hub?

Yours sincerely,

**Comment by ad-m** [comment]
I would like to point out that the locally built image was built correctly without any defects (manually tested). It seems that there was only something missing on the continous deployment stage.

**Comment by simonprev** [comment]
I just pushed the latest Accent image on Docker Hub https://hub.docker.com/r/mirego/accent/tags 👍 

I never succeeded in linking git tags hook with Docker Hub continuous builds…
