### ISSUE TITLE
Outdated demo

### ISSUE THREAD

**Issue by ad-m** [mirego/accent#179]
Hello,

In version 1.5.0 night mode was introduced. It's not available on demo. Which version of Accent demo are using? Can we upgrade it?

Greetings,

**Comment by ad-m** [comment]
I would notice that due of outdated demo I am unable to choose language and create project:

[demo.zip](https://github.com/mirego/accent/files/4585971/demo.zip)
Dropdown disappear when I press any key for search language.

**Comment by simonprev** [comment]
Just updated demo version with latest docker image 👍 #180 should help in seeing if the latest version is deployed on the demo site, thank you!

**Comment by ad-m** [comment]
I created # 180 because of, among others uncertainty about the version in the demo environment. Thank you for the project development and demo updates.
