### ISSUE TITLE
Can you make the integrity attribute on the javascript files optional?

### ISSUE THREAD

**Issue by samuelnygaard** [mirego/accent#190]
Im using accent througt a HTTPS proxy, which sanity check and compresses all ressources, this results in making the site unuseable in Chrome (do to forced integrity check in ressources) - since the SHA has changed.
![billede](https://user-images.githubusercontent.com/6584947/86931946-03d7ea80-c139-11ea-91cf-715e9447e327.png)

Is it possible to include a `SKIP_INTEGRITY` environment variable to skip the integrity attributes in the html?

Best regards
Samuel

**Comment by simonprev** [comment]
Closed by 8f1e8786, will be included in the next release 😄
