### ISSUE TITLE
can't create new version

### ISSUE THREAD

**Issue by rugbymauri** [mirego/accent#191]
if I to create a new version I get "new version cannot be created".

in the logs i got this

`
[error] Postgrex.Protocol (#PID<0.4905.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.23112.4> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.23112.4> was at location:

    :prim_inet.recv0/3
    (postgrex) lib/postgrex/protocol.ex:2837: Postgrex.Protocol.msg_recv/4
    (postgrex) lib/postgrex/protocol.ex:1879: Postgrex.Protocol.recv_bind/3
    (postgrex) lib/postgrex/protocol.ex:1771: Postgrex.Protocol.bind_execute/4
    (db_connection) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:595: DBConnection.execute/4
    (ecto_sql) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.execute/4

09:50:31.132 [error] #PID<0.23112.4> running Accent.Endpoint (connection #PID<0.23111.4>, stream id 1) terminated
Server: aaaaaaaaaaaaaaaaa:80 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
        (ecto_sql) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute/5
        (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
`

**Comment by RhabitAlexander** [comment]
I encountered the same problem.

**Comment by abdelhamid-attaby** [comment]
I am facing the same when adding a new language. I found there is a hard coded `timeout` here that may cause this issue:
https://github.com/mirego/accent/blob/0c1cea5951afaf6ba7e35d14b4ff3d162f92172b/config/config.exs#L9

**Comment by simonprev** [comment]
https://github.com/mirego/accent/commit/3325e5e9d8c1848dc6134d10d9a299331416e92c
