### ISSUE TITLE
Version 1.5.6 isn't tagged on docker hub

### ISSUE THREAD

**Issue by EspadaV8** [mirego/accent#198]
The last tagged version on Docker Hub is `1.5.5` - https://hub.docker.com/r/mirego/accent/tags?page=1&name=1.5.6

It looks like `latest` was tagged and may be `1.5.6` but doesn't have a named tag.

**Comment by simonprev** [comment]
Just pushed 1.5.6 on Docker Hub: https://hub.docker.com/layers/mirego/accent/1.5.6/images/sha256-4d09979834489981be7592a3aad659bd5cdf6e0c8cda86596f328b18436d138b

Sorry for the delay!

**Comment by EspadaV8** [comment]
Awesome, thanks
