### ISSUE TITLE
demo website doesn't seem to work

### ISSUE THREAD

**Issue by yennor** [mirego/accent#199]
I've just wanted to take a look at accent, but couldn't since the demo site doesn't seem to work properly.
No service to login is shown:
![Screenshot_20200822_080426](https://user-images.githubusercontent.com/6601243/90956665-42f29e80-e44e-11ea-902d-90a4101a5414.png)

**Comment by simonprev** [comment]
The login is back online, there was a env variable missing since the last 1.5.6 deploy
