### ISSUE TITLE
Host prebuilt releases

### ISSUE THREAD

**Issue by hauleth** [mirego/accent#20]
It would be nice to release prebuilt Erlang releases (potentially without ERTS) to simplify deployment.

**Comment by gcauchon** [comment]
I started working on a proposal that would include :
* a basic `docker-compose` setup for development,
* a script to build an OTP release in a minimal Docker image,
* a sample deployment to [Heroku](https://devcenter.heroku.com/articles/container-registry-and-runtime).

… stay tuned!

**Comment by simonprev** [comment]
A working Docker setup has just been added to the repo! 🎉 What would be the best way to host prebuilt images?

**Comment by hauleth** [comment]
GitHub releases?

**Comment by gcauchon** [comment]
We could publish images under Mirego’s Docker account. Building images can even be automated with Github webhooks

**Comment by gcauchon** [comment]
@simonprev let’s close this issue since the setup was addressed in recent development!

**Comment by simonprev** [comment]
Yup `accent:latest` is available on Docker Hub: https://cloud.docker.com/u/mirego/repository/docker/mirego/accent
