### ISSUE TITLE
Poor performance on Firefox

### ISSUE THREAD

**Issue by ad-m** [mirego/accent#203]
Hello,

I am notice pretty poor performance of Accent UI on Firefox 80.0 (64 bity) on Linux Mint. I don't have experience in UI performance bug reporting. On the same device in Brave Browser (Chromium-based) I don't notice any performance issue. I can not connect performance to specific activity. Just click around and my laptop fan is going fast.

On our instance (running in Docker from official instance) I started recording performance via build-in Firefox Developer Toolbar. 
Here is screenshot from Firefox to show issue:

![obraz](https://user-images.githubusercontent.com/3618479/92250117-5d575e00-eecb-11ea-9978-09d93890cf51.png)

We can see that FPS is going down sometime.

Here is call stack:

![obraz](https://user-images.githubusercontent.com/3618479/92250426-c0e18b80-eecb-11ea-87e6-fff7895e6ecb.png)

It looks like the performance issues are concentrated around one place and it exists on Javascript-side.

Here is recorded profile data: https://files.jawne.info.pl/private_html/2020_09_shaeDuokiateeShut4AiJohThahk0ieR8eiweecuquoteeNgux
In can be open in Firefox or at http://perfht.ml/ for futher analysis.

I have impression that there is some callback-loop:
![obraz](https://user-images.githubusercontent.com/3618479/92251645-6d703d00-eecd-11ea-8f72-18fcb9e9ed7f.png)

![obraz](https://user-images.githubusercontent.com/3618479/92251707-8678ee00-eecd-11ea-91db-dfc8eb89eb63.png)

Everything is in single file.

![obraz](https://user-images.githubusercontent.com/3618479/92252009-f38c8380-eecd-11ea-8476-f0e7755811ce.png)

I probably need to run without minitifaction the code to successfully get to the problem, but currently I'm not sitting down to that, so I'm leaving at least a trace.

Kind regards,
Adam Dobrawy

**Comment by filipcro** [comment]
Same thing happened on my MacBook. I got around 2.65 FPS in Firefox. I used provided demo application.

It works much better in Edge, but still slower than it should be. Those dropdowns are lagging a lot. 

![image](https://user-images.githubusercontent.com/19069893/104317896-e8321000-54de-11eb-9f55-75089042b6b2.png)

Those are my specs: 
![image](https://user-images.githubusercontent.com/19069893/104318166-4eb72e00-54df-11eb-95f7-ec41fcf84450.png)

**Comment by simonprev** [comment]
The power select component was the culprit. The simple selects are now native and will not consume so much memory

**Comment by ad-m** [comment]
How to verify which release have that fix? I would like upgrade Accent and verify there are no other problems here for my setup to support development of Accent.

**Comment by simonprev** [comment]
I think the select was refactored in 1.6.0 but you can upgrade to latest (now 1.8.3) since it does not break anything and you will have all the other fixes and features
