### ISSUE TITLE
 Refused to display frame because it set 'X-Frame-Options' to 'DENY'

### ISSUE THREAD

**Issue by tvb** [mirego/accent#210]
I added the following code block to my applications html `<head>`

```
    <script>
      window.accent=window.accent||function(){(accent.q=accent.q||[]).push(arguments);};
      accent('init',{h:'https://my-app.herokuapp.com',i:'xxxxx-xxxx-xxxxx-xxxxxxx'});
    </script>
    <script async="" src="https://my-app.herokuapp.com/static/jipt/index.js"></script>

```

But, I get the following error in the browser console. I am unable to login because of this.

>Refused to display 'https://accounts.google.com/o/oauth2/v2/auth?client_id=xxxxxxxx-xxxxxxxxxxxxxxxx.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fmy-app.herokuapp.com%2Fauth%2Fgoogle%2Fcallback&response_type=code&scope=email' in a frame because it set 'X-Frame-Options' to 'DENY'.

**Comment by simonprev** [comment]
This is an HTTP header sent by your application server: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

You will need to remove the header to allow the iframe to run inside your application.
