### ISSUE TITLE
Github integration error

### ISSUE THREAD

**Issue by alteoxCOM** [mirego/accent#216]
Hello,

we are trying to integrate the GitHub extension.

Starting accent via docker, all starts fine.
But when adding a GitHub  integration (token and repo all setup + accent.json on GitHub)
I only receive an error: The integration could not be added.

Is there a way to debug more and see what is the problem?

In docker output I only see:
accent         | 10:10:23.453 request_id=Fkl-IULD8zbhhWMAAAMh [info] POST /graphql
accent         | 10:10:23.477 request_id=Fkl-IULD8zbhhWMAAAMh [info] Sent 200 in 23ms
accent         | 10:10:23.592 request_id=Fkl-IUsPFNgwq00AAAMx [info] POST /graphql
accent         | 10:10:23.621 request_id=Fkl-IUsPFNgwq00AAAMx [info] Sent 200 in 29ms

Thanks for your help.

**Comment by simonprev** [comment]
Can you show me a screenshot of the error in the app? The required fields are `[:repository, :default_ref, :token]` for the integration, maybe the default value for `ref` (master) is not sent to the API?

**Comment by simonprev** [comment]
Fixed by 5e965d88efcbfb7277aceb221960d8e16d337496
