### ISSUE TITLE
Invalid import of Gettext multiline strings

### ISSUE THREAD

**Issue by hedin-hiervard** [mirego/accent#217]
First of all, thank you for your work. This is a great tool and will help my project greatly. 

I'm trying to import a .po file. This is the correct multiline file example according to gettext spec: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

```
msgid "LEVEL_TUTORIAL2_STRECH_YOUR_LEGS"
msgstr ""
"From Chambers you control the whole Tower.\n"
"Sometimes a personal presence is needed.\n"
"[key:use_room] to stretch your legs."
```

It's imported as:

```

From Chambers you control the whole Tower.

Sometimes a personal presence is needed.

[key:use_room] to stretch your legs.
```

Note the extra carriage returns.

Expected import result:

```
From Chambers you control the whole Tower.
Sometimes a personal presence is needed.
[key:use_room] to stretch your legs.
```

**Comment by simonprev** [comment]
Fixed by https://github.com/mirego/accent/commit/2b649acc8842865a8667f376a4c7aab49cf5a264
