### ISSUE TITLE
"Text is empty ("" or null value)" is filtering empty strings out

### ISSUE THREAD

**Issue by hedin-hiervard** [mirego/accent#218]
When I check the filter nothing is shown despite the fact I have multiple untranslated strings. Please see the screenshots.

![image](https://user-images.githubusercontent.com/961822/99909572-adcfa200-2ce9-11eb-8d56-ffddca292ae8.png)
![image](https://user-images.githubusercontent.com/961822/99909577-b58f4680-2ce9-11eb-8de3-a49a59c8029b.png)
![image](https://user-images.githubusercontent.com/961822/99909586-be801800-2ce9-11eb-8ccb-a160bccf834b.png)

**Comment by simonprev** [comment]
Thanks for the report! Can you tell me which format you used to sync the strings? (JSON, Android XML, etc)

**Comment by hedin-hiervard** [comment]
> Thanks for the report! Can you tell me which format you used to sync the strings? (JSON, Android XML, etc)

Hi,
I use gettext (.po files) for all my projects and this also applies to my other bug reports.

**Comment by simonprev** [comment]
Fixed by c937a2ace10bd35c0d4b9e65315daa71f20a4467 and 8c94168c0fdbe9a8a150bfdb4bf8bc2e11af07b2

Not released in a tag but I will cut a release soon (`latest` on Docker Hub has the fixes)
