### ISSUE TITLE
Review queue doesn't respect language filter

### ISSUE THREAD

**Issue by hedin-hiervard** [mirego/accent#219]
Steps to reproduce:

1. Create multi-language project
2. Make sure some of the strings are in the unreviewed state.
3. Go to 'review' button.
4. Choose the language.
5. Click 'review' on the first string.

BUG!
The updated list will contain strings from all languages.

What is expected:
The review queue always shows only the strings from the language selected from the top combobox.

**Comment by simonprev** [comment]
Fixed by https://github.com/mirego/accent/commit/c736fd6a4050f6ec1d57de93a2e1e06f1fa51f7d
