### ISSUE TITLE
Import/Export Excel files

### ISSUE THREAD

**Issue by hauleth** [mirego/accent#22]
This would help when working with some clients that are less tech savvy.

**Comment by simonprev** [comment]
The goal of Accent is to bind the translations with files used in the project. Do applications use xlsx as a translation format?

The format sounds easy to parse but can be tricky to "emit" I think

**Comment by hauleth** [comment]
I do not think that there is any tool that uses XLSX as input format except wetware. Personally I think it is easier to emit than to parse, however it should be quite easy. Alternatively instead of Excel files you could provivde support for CSV values. It should be much easier and would provide support for vast amount of spreadsheets.
