### ISSUE TITLE
Failure when building OTP with master `4ad749f`

### ISSUE THREAD

**Issue by hedin-hiervard** [mirego/accent#223]
Please see the log attached.

[accent_build_failure.log](https://github.com/mirego/accent/files/5609580/accent_build_failure.log)

**Comment by hedin-hiervard** [comment]
Also tried with `--no-cache` flag — the result is the same.

**Comment by simonprev** [comment]
Validated with 09e4301aea447998d76050f95719730a79832f38 with an without `DOCKER_BUILDKIT` and everything works correctly
