### ISSUE TITLE
Put the MASTER language at the top on this page

### ISSUE THREAD

**Issue by Fma965** [mirego/accent#227]
I think it would be a good idea to to put the MASTER language at the top on this page

![image](https://user-images.githubusercontent.com/1707290/103314939-14985780-4a1c-11eb-9276-460226eff804.png)
![image](https://user-images.githubusercontent.com/1707290/103314946-182bde80-4a1c-11eb-9a39-09e665e3bb50.png)

my translators have requested this feature :)

**Comment by simonprev** [comment]
Fixed by https://github.com/mirego/accent/commit/8b84d0f1a523ac2a5bbd1ce09494991db624e79f
