### ISSUE TITLE
Discord webhook not working on 1.7.0

### ISSUE THREAD

**Issue by Fma965** [mirego/accent#228]
Discord webhook not working on 1.7.0

Nothing comes through on discord, was working fine on older versions, I think 1.6.3 but not 100%

**Comment by Fma965** [comment]
Actually it seems GitHub hooks also don't work

**Comment by simonprev** [comment]
How are you running the application? We have a special clause for not running the async task like sending a webhook when the app is running inside `iex` like with `iex -S mix phx.server`

**Comment by Fma965** [comment]
I was just running it in a docker container, nothing special

**Comment by Ellpeck** [comment]
Hi, any update on this? The Discord webhook still has no effect running 1.12.3 using Docker. There's nothing in the logs about it, either, unfortunately.

**Comment by simonprev** [comment]
@Ellpeck Can you try it with another URL? The webhook has no special connexion to Discord beside the formatted payload. Can you use https://pipedream.com/requestbin to try it with another URL to see if the request is made?

**Comment by Ellpeck** [comment]
Hi, I tried to use a RequestBin URL as the webhook URL in my Accent installation, and then I tried syncing using the CLI. No requests were logged in the Pipedream inspector. 

Here is my setup, just in case I did anything wrong:

![image](https://user-images.githubusercontent.com/5741138/217199105-d10376e5-a339-4243-bd88-328b3b44429f.png)

![image](https://user-images.githubusercontent.com/5741138/217199196-183de92a-ce95-4d47-82ac-d4b7a963bf5c.png)

The single `GET` request is me trying out the webhook URL in my browser to make sure it does *something*.

**Comment by Ellpeck** [comment]
Hi! I tried with the RequestBin URL, and two POST requests are made when two of the actions are selected in the webhook settings on Accent. Here is the full info of one of them:

```
{"event":{"method":"POST","path":"/","query":{},"client_ip":"94.219.87.130","url":"https://eo5txrdlsyjxs22.m.pipedream.net/","headers":{"host":"eo5txrdlsyjxs22.m.pipedream.net","content-length":"126","user-agent":"hackney/1.18.1","content-type":"application/json"},"body":{"text":"**API Client** just synced a file: *Localization*\n\n**Stats:**\nConflict on proposed: *1*\nConflict on slave: *18*"}},"context":{"id":"2LP6mmlwmETiCMcj8rJwFhitF49","ts":"2023-02-07T09:02:11.334Z","pipeline_id":null,"workflow_id":"p_aNCpL1Y","deployment_id":"d_kPsrG3BE","source_type":"COMPONENT","verified":false,"hops":null,"test":false,"replay":false,"owner_id":"u_owhM2pJ","platform_version":"3.36.1","workflow_name":"RequestBin","resume":null,"trace_id":"2LP6mnplcraa3edLAmJamQUOFCi"}}
```

I hope this is helpful for fixing this issue!

**Comment by Ellpeck** [comment]
Hi, reporting back again from version 0.15.0. I tried this again, setting up the webhook again and everything, and it prints this info this time around: 
```
accent    | 11:12:02.765 hook_service=discord hook_url=https://discord.com/api/webhooks/<my webhook url> [info] Responded 400 in 251ms
accent    | 11:12:02.909 hook_service=discord hook_url=https://discord.com/api/webhooks/<my webhook url> [info] Responded 400 in 276ms
```

**Comment by simonprev** [comment]
Oh this means that the request Accent is sending to discord is not valid 🤔 I will validate the payload with the Discord API

Thanks for the report! 👍

**Comment by farfalk** [comment]
Hi, I'm using the latest version (1.20.1) deployed in a docker container, and the Discord Webhook events seemingly don't get sent at all.

I tried using a requestbin endpoint as a test, and it never receives anything. 

My test configuration:
![immagine](https://github.com/mirego/accent/assets/9095842/54565adf-85cd-42e8-ba68-d093b3986b46)
