### ISSUE TITLE
Allow renaming already uploaded files

### ISSUE THREAD

**Issue by hauleth** [mirego/accent#23]
Sometimes when you upload files "as is" these do not have meaningful names, ex:

- `translations.pot`
- `strings.xml`

It would be useful to rename them to have meaningful names like: `iOS app` and `Web app`.

**Comment by simonprev** [comment]
The API already support passing a `document_name` parameter but the web app doesn’t provide a way to specify it. In the upload form we could list the available file or use a text input to manually enter the filename. And of course provide a way to edit the filename on the "Files" view.
