### ISSUE TITLE
Demo version is down

### ISSUE THREAD

**Issue by obrassard** [mirego/accent#230]
👋 hey ! Not sure if it’s a known issue or not, but it looks like the demo app is down on heroku : http://demo.accent.reviews/

![C9681392-C3B3-43D9-968B-A62FA412BDF5](https://user-images.githubusercontent.com/17227551/103968659-3a1b1480-5132-11eb-989b-30b872c9f630.png)

**Comment by simonprev** [comment]
The demo app uses a free dyno from Heroku so it somtimes can be down. It is back now without a restart so I will close this issue, thank you! 😄
