### ISSUE TITLE
Better support for adding existing translations

### ISSUE THREAD

**Issue by filipcro** [mirego/accent#231]
Hi. We have a project with 15 languages and 850 translation keys. Master language has all translations, but other language have many missing. We need a way to find them. 

I would like to have the following options to support this use case:

- mark translations as 'Reviewed' while importing them
- use `null` as default value while adding languages (so missing translations can filtered and added)

**Comment by simonprev** [comment]
Added in 43055188c36bc42887bc1dda0a86e56b9147dd24 and e9ec74ef611976cfdc5c34ccf913cedabf62cb93

🎉

**Comment by filipcro** [comment]
Thank you. This features greatly increased possible use cases for this project
