### ISSUE TITLE
GitLab integration support

### ISSUE THREAD

**Issue by EspadaV8** [mirego/accent#234]
Similar to the GitHub integration, it'd be great if there was also a GitLab integration that works in a similar way.

**Comment by alexanderadam** [comment]
People using GitLab might be interested that [@bbfdpns' OAuth PR was now merged](https://github.com/mirego/accent/pull/264)

**Comment by simonprev** [comment]
The GitHub integration has been removed from the codebase. We use GitHub Actions to push and pull translations update.

**Comment by alexanderadam** [comment]
> We use GitHub Actions to push and pull translations update.

Not relevant to the issue but have you documented your GitHub Actions setup somewhere publicly? 👀
