### ISSUE TITLE
Invalid export of multi-line strings

### ISSUE THREAD

**Issue by hedin-hiervard** [mirego/accent#261]
It's related to https://github.com/mirego/accent/issues/217

I'm using PO (gettext) format for import and export operations. 

1. Try setting the following text in UI:

(a) 
```
line1
line2
```

or 

(b) 
```
line1

line2
```

or 

(c)
```
line1


line2
```

2. Export.
3. What I see: every time the exported data is the same:

```
msgstr "line1\n"
"line2\n"
```

4. What I expect: different output.

(a)
```
msgstr "line1\n"
"line2\n"
```

(b)
```
msgstr "line1\n"
"\n"
"line2\n"
```

(c)
```
msgstr "line1\n"
"\n"
"\n"
"line2\n"
```

**Comment by simonprev** [comment]
I refactored the Gettext serializer in v1.13.0 that I just released. You can open a new issue if there are still problems
