### ISSUE TITLE
Cannot select spanish (es) as a project language

### ISSUE THREAD

**Issue by Elanis** [mirego/accent#269]
![image](https://user-images.githubusercontent.com/7013446/132380835-882bdd09-dc8f-420b-bb62-418e26e7fdbf.png)

Some spanish variants cannot be selected while adding a language to a project.

**Comment by simonprev** [comment]
They can’t be _selected_ at all? What is the result of clicking on an item in the dropdown?

**Comment by simonprev** [comment]
All languages are defined here: https://github.com/mirego/accent/blob/master/priv/repo/languages.json

Is there a missing "Spain" entry? I don’t know where I got the list from initially 🤔

**Comment by barnaclebarnes** [comment]
You can select other Spanish locales but not plain Spanish es. The funny thing is that the language is in the data file:


  ```
{
    "name": "Spanish",
    "slug": "es",
    "iso_639_1": "es",
    "iso_639_3": "spa",
    "locale": "es-ES",
    "android_code": "es-rES",
    "osx_code": "es.lproj",
    "osx_locale": "es"
  },
```

The plain Spanish just doesn’t appear in the list when you search for Spanish.

**Comment by simonprev** [comment]
Fixed in https://github.com/mirego/accent/releases/tag/v1.10.0
