### ISSUE TITLE
Some text is hidden or displayed with formatting in Review section

### ISSUE THREAD

**Issue by Ellpeck** [mirego/accent#279]
It seems like some text from other languages gets removed or displayed differently in the "Review" section when it has a HTML-like structure, but shouldn't actually extend into any HTML entities. This issue does not occur in the "All strings" section.

Here are some screenshots that explain this issue very well. As you can see, the `<i tb>` part is hidden and replaced with italics in the first screenshot.

![image](https://user-images.githubusercontent.com/5741138/150825338-0a192324-18e7-4bdf-ae77-483e94139088.png)

![image](https://user-images.githubusercontent.com/5741138/150825388-fd3c2d7b-3adb-49b4-8caf-895f137010b3.png)

I think, in general, it is quite confusing to have text displayed this way (even in cases where it would convert to bold or italic text in a real situation), because it hides that part of the string from the user, which might make them forget to add it.

I'm on version 1.9.1.

**Comment by simonprev** [comment]
Fixed in https://github.com/mirego/accent/releases/tag/v1.10.0
