### ISSUE TITLE
How to add translators?

### ISSUE THREAD

**Issue by tombayley** [mirego/accent#292]
Am I wrong in thinking someone can signup and view/translate a list of projects without being invited as a Owner/Admin/Developer/Reviewer?
The way the documentation is written sounds like that is possible.

Say I create a project called X.
A person wanting to translate then signs in with Google/GitHub/etc.
But that person cant see project X. They have their own "space".

Am I missing something or is this not possible?

I thought there would be a "Translator" role alongside Owner/Admin/Developer/Reviewer.

**Comment by TheMen4ce** [comment]
I guess you have to add a translator as a "reviewer"

**Comment by simonprev** [comment]
Yes translator are "reviewer" in the roles list. A user can only see projects that they have been added as collaborators on.
