### ISSUE TITLE
custom language wrong slug and name in graphql api

### ISSUE THREAD

**Issue by tuxes3** [mirego/accent#298]
Hi,

I have a project with 3 languages: German (Main) `de`, German - Custom `de_custom`, French `fr`

As you see I renamed a language to fit my business case. (We need to be able to provide multiple accents per language, not only the default ones) 

The Graphql api still returns the original language name and slug.

**Prerequisites**
![image](https://user-images.githubusercontent.com/5341293/171180112-f7b0d0a8-2316-4aef-8701-e4a1782ab28e.png)

**Query**
This query should give me all files and all languages present in the project.  
```graphql
query Translations($projectId: ID!) {
  viewer {
    project(id: $projectId) {
      documents {
        entries {
          id
          path
          format
        }
      }
      revisions {
        isMaster
        id
        language {
          slug
          name
          id
        }
      }
    }
  }
}
```

**Excepted Result**
```json
...
          {
            "id": "~~some id~~",
            "isMaster": false,
            "language": {
              "id": "~~some id~~",
              "name": "German, Custom",
              "slug": "de_CUSTOM"
            }
          }
...
```

**Actual Result**
```json
...
          {
            "id": "~~some id~~",
            "isMaster": false,
            "language": {
              "id": "~~some id~~",
              "name": "German, Switzerland",
              "slug": "de-CH"
            }
          },
...
```

**Comment by simonprev** [comment]
The overwrites are not propagated in the language. We have name and slug on the revision object 😄

**Comment by tuxes3** [comment]
You are right. Thanks for helping!
