### ISSUE TITLE
Overzealous linting rule

### ISSUE THREAD

**Issue by AcidWeb** [mirego/accent#301]
The "First letter of translation does not match case of the master’s" check is overzealous in case of languages that don't use latin alphabet.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/3713734/173755789-f0d364a3-304c-457a-bcb0-611493c50318.png">

**Comment by simonprev** [comment]
https://github.com/mirego/accent/commit/e04dccf6bd418f630fbcee3092fd1795469b1716
