### ISSUE TITLE
Plurals are not returned as plurals

### ISSUE THREAD

**Issue by tompesman** [mirego/accent#303]
Hi Accent Team,

Thank you for your work on this project! 👏 

We have an issue where the plurals are not returned as plurals, but as separate translations. I've verified in the `translations` table that the `plurals == true` and in the `Langue.Formatter.Android.Serializer` the entries all are `plurals == false`. So therefore I assume not all the fields in the `Langue.Entry` are set. When we check the https://github.com/mirego/accent/blob/master/lib/accent/translations/translations_renderer.ex#L46 file the `Langue.Entry` struct is not completely set and the default for plural is false. 

By setting the value in the struct solves it for my test, but I'm not sure if the other fields need to be considered as well. 

Cheers!

**Comment by simonprev** [comment]
Can you post a part of your localization file that has plurals and is not handle correctly? I will be able to debug it locally and add some tests, thanks!

**Comment by tompesman** [comment]
Hi Simon,

I've added a test to `test/web/controllers/export_controller_test.exs`

```elixir
  test "export with default order 2", %{conn: conn, project: project, revision: revision, language: language} do
    document = %Document{project_id: project.id, path: "test2", format: "android_xml"} |> Repo.insert!()
    %Translation{revision_id: revision.id, key: "days.one", corrected_text: "bar", proposed_text: "bar", plural: true, document_id: document.id, file_index: 2} |> Repo.insert!()
    %Translation{revision_id: revision.id, key: "days.other", corrected_text: "foo", proposed_text: "foo", plural: true, document_id: document.id, file_index: 1} |> Repo.insert!()

    params = %{order_by: "", project_id: project.id, language: language.slug, document_format: document.format, document_path: document.path}
    response = get(conn, export_path(conn, [], params))

    assert response.resp_body |> IO.inspect == "--"
  end
```

You can see that the `IO.inspect` returns `plural: false` instead of `plural: true`.

An example is in the `test/langue/android/expectation_test.exs:28` file, but as an integration test this actually fails.
