### ISSUE TITLE
Authentication with e-mail and service 

### ISSUE THREAD

**Issue by Wessergame** [mirego/accent#314]
Is it possible to enable registration in accent? Or is there any way to configure the api of different services so that it redirects not to the local ip but to the canonical url? Accent is in docker with a 127.0.0.1:4000 address, if you specify a canonical url in the api, it will give an error. If everything is done correctly, it will redirect the request to 127.0.0.1:4000, which, of course, I will not be able to process

**Comment by simonprev** [comment]
Next version will use the `CANONICAL_URL` correctly to redirect using `x-forwarded-port` header
