### ISSUE TITLE
I get an 500 Interal Server Error if I select a language

### ISSUE THREAD

**Issue by chrisonline** [mirego/accent#331]
The main language is working after uploading the file.
But when I add a new language and select "All Strings" with the new language, I see a 500 Internal Server error in the console and nothing loads:
![image](https://user-images.githubusercontent.com/2077218/208887091-4b3d5e0c-82c6-4d9e-96df-c6909303dd7e.png)

Logs:
![image](https://user-images.githubusercontent.com/2077218/208886993-c99a435f-db62-4bfd-9196-fb3ad661f169.png)

Installed via Docker compose.

**Comment by simonprev** [comment]
Fixed on https://github.com/mirego/accent/releases/tag/v1.13.0
