### ISSUE TITLE
Do not use `System.get_env/1` in config

### ISSUE THREAD

**Issue by hauleth** [mirego/accent#34]
The problem with such is that it requires `config.exs` to be evaluable at startup while Erlang releases do not contain such code. Currently the best solution is to call some function in `Application.start/2` callback that will fetch values from config and set them where these are needed. Alternatively there is "common" patter to use `{:system, "ENV_NAME"}` and `{:system, "ENV_NAME", default}` patterns and then fetch data whenever needed.

**Comment by simonprev** [comment]
@gcauchon will tackling this soon as part as the "OTP release" refactor in #20 . Currently, we deploy our instance on Heroku with `mix phx.server` so this is not an issue for us. But OTP release will be a nice addition to the app 😄

**Comment by gcauchon** [comment]
I updated my tasks list to explicitly include support for environment variables in the OTP release.
