### ISSUE TITLE
Will this work with self-hosted bitbucket instance? 

### ISSUE THREAD

**Issue by foxnoodles** [mirego/accent#346]
The title is self-explanatory I think. So will this work on local bitbucket git instance?

**Comment by remi** [comment]
@foxnoodles I’m not sure I understand what you mean. Accent doesn’t need a git repo to work. Are you referring to `GITHUB_*` and `GITLAB_*` environment variables for authentication?

**Comment by foxnoodles** [comment]
Can accent sync( pull from and push to) Bitbucket repo which is self-hosted on the company's servers(not on bitbucket.com).  Not sure which part of my question was unclear.

**Comment by remi** [comment]
Unfortunately, the GitHub integration Webhook only works with GitHub. It doesn’t work with any other Git repo.
