### ISSUE TITLE
Machine translation error

### ISSUE THREAD

**Issue by Ellpeck** [mirego/accent#347]
When pressing the "Translate from this text" button, the following exception occurs on the serverside:
```
accent    | ** (exit) an exception was raised:
accent    |     ** (FunctionClauseError) no function clause matching in String.upcase/2
accent    |         (elixir 1.14.2) lib/string.ex:831: String.upcase(:unsupported, :default)
accent    |         (accent 1.14.1) lib/machine_translations/provider/deepl.ex:44: Accent.MachineTranslations.Provider.Accent.MachineTranslations.Provider.Deepl.translate/4
accent    |         (accent 1.14.1) lib/machine_translations/machine_translations.ex:22: anonymous fn/5 in Accent.MachineTranslations.translate/4
accent    |         (elixir 1.14.2) lib/enum.ex:4249: Enum.flat_map_list/2
accent    |         (accent 1.14.1) lib/graphql/resolvers/machine_translation.ex:20: Accent.GraphQL.Resolvers.MachineTranslation.translate_text/3
accent    |         (absinthe 1.7.0) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
accent    |         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
accent    |         (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
```
This causes the text box to always stay grayed out until reloading the page, and the string never to be translated. 

It should be noted that translating an entire file through the Files section *does* work with my current setup, so the connection to the translation API doesn't appear to be the issue.

**Comment by simonprev** [comment]
Oh I see that we don’t handle "unsupported" languages DeepL and Google Translate provider. What language are you trying to translate? (source and target)

**Comment by Ellpeck** [comment]
I'm trying to translate from English into German, which works correctly using the DeepL provider in the Files section, but not in the Review section. So this doesn't seem to have anything to do with unsupported languages at first glance.

**Comment by simonprev** [comment]
When you translate from the File list, you can select the target language, in your case `German (de)` but when you translate in Review it takes the slug of your translated language.

https://user-images.githubusercontent.com/464900/222449881-ccd67e04-05e6-4b5e-97b2-1a2dd075a3d6.mov

What does your Languages section looks like?

<img width="940" alt="image" src="https://user-images.githubusercontent.com/464900/222450039-0a7941e8-be55-4df6-882a-527391d247ea.png">

**Comment by simonprev** [comment]
Yep the "unsupported" error should be handled, I will fix it in the next version, thanks for the report! 👍

**Comment by kevinam99** [comment]
Is this open for resolution?
