### ISSUE TITLE
After Adding a new Language and Sync it adds in the Language all Keys twice

### ISSUE THREAD

**Issue by NewtTheWolf** [mirego/accent#349]
master.json:
```json
{
  "hello": "Hello",
  "hello_name": "Hello, {name}!",
  "test": "This is a test"
}
```

after I add a language (no matter if with or without empty strings)
and no matter if I adjust/update the strings directly

I do a sync, the values are always the same as the master.json (even if I have translated the values before) and because of this I have all keys duplicated when I initially add a language.

Without empty strings and without sync:
![grafik](https://user-images.githubusercontent.com/59208097/222716907-8af1c502-954f-482c-8cfa-138d04cf137c.png)

After the sync:
(it doesn't matter how I use the CLI `accent sync` and `accent sync --add-translations`)
![grafik](https://user-images.githubusercontent.com/59208097/222717477-1e834302-5fe7-4d98-a39b-5bf38e236fdf.png)

and if i do an export `accent export` and i have already added strings in de, the `en.json` is just empty
after a sync it fills with the values from the master, and I have all keys twice as shown in the 2nd picture

**Comment by simonprev** [comment]
This is a duplicate from: https://github.com/mirego/accent/issues/338

It has been resolved in the latest version 1.14.1 😃
