### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by cesar-mso** [mirego/accent#351]
Hi!
Just tried to check out the "demo" from your website (and in here), but get the following error
![Capture](https://user-images.githubusercontent.com/14789802/226598388-b1177108-ef25-4ce7-9cda-7b1322511c75.PNG)

Apologies if this is not the correct place to flag this, please delete if needed!

**Comment by simonprev** [comment]
Link has been updated to the new fly.io free app on [accent-demo.fly.dev](https://accent-demo.fly.dev/) 👍
