### ISSUE TITLE
why is the changelog not up to date?

### ISSUE THREAD

**Issue by NewtTheWolf** [mirego/accent#352]

**Comment by marcantoinefortier** [comment]
The change log is not to date regarding what exactly? 👀

**Comment by NewtTheWolf** [comment]
the changlog only goes up to version 1.12, but currently version 1.14 is released

**Comment by simonprev** [comment]
Changelog is now up to date. It is a manual task so I have to take the time to actually write it.

If you want up to date information of what what added, you can always look at the commit history, there is not a ton of commit so it’s easy to see what was done 😄

**Comment by NewtTheWolf** [comment]
Make notes and enter them into ChatGPT to reduce your workload. Alternatively, follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#effort) standard and use the "Unreleased" keyword. This way, when you release, you only have to update the version.

it is pretty hard to look into the Commit History (yes i can Try) but i think this idea would be easier for everyone 😄
