### ISSUE TITLE
CLI Export does not work on MacOS

### ISSUE THREAD

**Issue by p-barabas** [mirego/accent#357]
I installed accent cli from npm package using: rpm install -g accent-cli
Current version is: accent-cli/0.13.3 darwin-arm64 node-v19.6.1
OS version: MacOS Ventura 13.1.
Computer: MacBook Pro with M1 chip

When I want to export using accent export command with a proper config.json file, the following happens:
Fetch config in accent.json... API Client ✓

Writing files locally

So no string resource files are downloaded. The same works with sync.
If I downgrade accent-cli to 0.10.3, export woks fine. 
I checked some versions meanwhile, the latest working is 0.11.0.

**Comment by simonprev** [comment]
I think there was a missing library in early version of the cli. Try again with the latest 😄
