### ISSUE TITLE
Feature request: Separate push and pull cli methods

### ISSUE THREAD

**Issue by ChiefORZ** [mirego/accent#361]
As the title insists, it would be awesome if we have control over push and pull separately.
Sometimes you need to pull all translations without pushing your local changes (e.g. when pulling origin changes to create a PR automatically).
And sometimes you want to push without pulling (e.g. when a feature branch gets merged into main)

PS: maybe i am missing something and the "pull" behaviour is the `accent export` method, but this command is only ever exporting the main language for us.

**Comment by simonprev** [comment]
The next version of the CLI will have the option `no-local-write` on the sync operation. If the export still does not export target languages, you should open a new issue with your `accent.json` config and your project file structure 😃

**Comment by fcastell** [comment]
This new option is not available when I install accent from npmjs:
` ›   Error: Unexpected argument: --no-local-write`
I think the last version of the cli is not deployed on npmjs.
