### ISSUE TITLE
Ignore specific file on sync

### ISSUE THREAD

**Issue by flavienbesseau** [mirego/accent#370]
@simonprev Hello !
Thank for this amazing project
I can see you are still working on the project.
I don't know if you'll see this message but let's try:
In accent, I inserted 3 json files in english (product, welcome & flight). I made the translation in Accent.
When i put in my console 'accent sync' with: 
<img width="605" alt="image" src="https://github.com/mirego/accent/assets/64224833/23da1d01-60d8-4c40-88c4-320f5c7cd1ee">
My problem is i want to get only flight & product, but here i get every translations: 
<img width="211" alt="image" src="https://github.com/mirego/accent/assets/64224833/f4fbb9ae-a243-4edf-82b4-d01395a80120">
I  tried everything and i'm fully blocked.
Is it possible to get only a part of all translation?
 Thanks a lot

**Comment by simonprev** [comment]
Hello!

You mean you have a file in Accent that you don’t want to sync with your project? We sync every file because if a sync adds a file (like when a colleague adds a new feature) we absolutely want to create the file 😄 

Maybe we need a "ignore" files section in the config? 🤔

**Comment by simonprev** [comment]
The behaviour has been changed to only sync files found in the filesystem as the file addition/removal is already handled by git.
