### ISSUE TITLE
Changelog Updates

### ISSUE THREAD

**Issue by NewtTheWolf** [mirego/accent#371]
Make notes and enter them into ChatGPT to reduce your workload. Alternatively, follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#effort) standard and use the "Unreleased" keyword. This way, when you release, you only have to update the version.

it is pretty hard to look into the Commit History (yes i can Try) but i think this idea would be easier for everyone 😄

_Originally posted by @NewtTheWolf in https://github.com/mirego/accent/issues/352#issuecomment-1709920063_

**Comment by simonprev** [comment]
I have something generated by ChatGPT that looks pretty good, I will push it soon 👍

**Comment by simonprev** [comment]
https://github.com/mirego/accent/blob/master/CHANGELOG.md
