### ISSUE TITLE
Do not delete strings after sync

### ISSUE THREAD

**Issue by marekkondracki** [mirego/accent#394]
I work in small team. Every day someone add new strings to the accent, but if I sync file with new strings, then another developer sync file without "my" strings, he deleted my previous strings. It is hard to maintenance. Is it possible to not delete strings that were send to the accent?

Option to add new strings in accent panel will solve this problems.

**Comment by simonprev** [comment]
Hello! The workflow that should be used for Accent is to sync the "main" trunk of your git repository. So if the main branch is `master`, only when you are in the `master` branch should you sync to Accent! That way, any conflicts generated by you and the other developer will be resolved by git.
