### ISSUE TITLE
Google Auth login fails in Firefox

### ISSUE THREAD

**Issue by aardvarkk** [mirego/accent#41]
I set up a Heroku deployment of Accent and things seem to be working reasonably well in Chrome. In Firefox, however, when I click "Login with Google", the popup appears as expected (and closes when I select which account to use), but then... nothing happens back on the original page. I took a look at the console and found an error that triggered on each login attempt:

`popup_closed_by_user`

The error is being fired from the following function area (in the minified JS):

```
this.session.googleAuth.attachClickHandler(t,{},
  function(t){
    return e._authSuccess(t)
  },
  function(e){
    return window.console.error(e)
})
```

This is how the console looks after several attempts:

![image](https://user-images.githubusercontent.com/1251092/39892015-14f1e360-5454-11e8-8593-e1bb9dea4c62.png)

Not sure what other info I can provide. For now I can work around this by just using Chrome for logging in, it's just not my primary browser. I'm currently using Firefox Quantum v60.0.

**Comment by simonprev** [comment]
Are you sure you don’t have a browser extension that blocks Google scripts like *AdBlocker*, *uBlock*, *Ghostery*…?

The `popup_closed_by_user` is always caused by this.
