### ISSUE TITLE
Just In Place Translations

### ISSUE THREAD

**Issue by tiagofcp** [mirego/accent#410]
Are Just In Place Translations working? I always get a semi transparent layer above the page and does not work

**Comment by simonprev** [comment]
I just fixed the script and I also added a page example inside every projects to showcase the feature and use the real script 🎉  The page lives on "http://your-host-name/app/projects/:id/jipt-example"
<img width="1128" alt="image" src="https://github.com/mirego/accent/assets/464900/e66974d4-82b0-441e-98b1-e39431ffce6f">
