### ISSUE TITLE
Serving as translation server

### ISSUE THREAD

**Issue by hansyulian** [mirego/accent#414]
Hi nice project!

I wonder is there a way for me to use as self hosted translation server? so like is there a way to somehow access `{host}/locales/en/translation.json` publicly

**Comment by simonprev** [comment]
👋 Yes, all documents can be viewed with the `/export` route with a couple of parameters:

```
http://localhost:4009/export?inline_render=true&language=fr&project_id=my-project-uuid&document_path=ticketss&document_format=json
```

It will respond with a "text/plain" Content-Type with the content of the document in the format you requested.
