### ISSUE TITLE
Can't click on the pen button in the review tab

### ISSUE THREAD

**Issue by RappyTV** [mirego/accent#419]
When I click on that little pen button (I don't even know what it's supposed to do) in the review tab I get this error message:
![image](https://github.com/mirego/accent/assets/72705182/f44c4b22-e78a-4f3a-b499-a9c4220178d3)

**Comment by simonprev** [comment]
We removed the button in the Review tab, now it’s only in the "Translator" tab (replaced for the Reviewer tab when the role of the user is Translator). There was a missing translations in the webapp 🥲 It’s fixed on master
