### ISSUE TITLE
Review - Some translations are in the wrong column

### ISSUE THREAD

**Issue by guyaumetremblay** [mirego/accent#422]
Hi,

A new bug has been introduce recently: 
Say 
- we have 2 languages: French and English
- Our master language is French
- We want to review English locales

Both languages are now displayed side by side but... some items are in the wrong column! 
If we remove the English in the language selector, all the French items are correct. But as soon as we add English, we find some French items in the English column and "vice versa".

It add some steps for us, the dev, when we pull from accent as we sometime need to put the content entered by the translator in the right language!

**Comment by guyaumetremblay** [comment]
Hi @simonprev , 
Unfortunately, I can't give you a screenshot (all our translation have been reviewed since, so the bug is not there anymore).
But, about our project: 
- The sync is using Circumflex (so, mobile app, accentApiVersion 2) with a single translation file containing both languages. 
- This project is hosted on https://mirego.accent.review , using 1.20.1 

The thing is that if I select only French in the review section, the display is correct. But if I add English in the language selector (so it display side by side), everything is mixup!

**Comment by simonprev** [comment]
> This project is hosted on https://mirego.accent.review/

Oh cool, that I have access to the database since I’m the only developer working on Accent 😄 I will be able to debug it 👍

**Comment by guyaumetremblay** [comment]
Nice! 
BTW, fyi, this specific project is also facing this weird issue : #330

**Comment by simonprev** [comment]
This seams to be the same issue as #330. Your project "sync" operation is syncing English in the French master language.
