### ISSUE TITLE
Switch sides in reviews page

### ISSUE THREAD

**Issue by makkmarci13** [mirego/accent#448]
This should be the normal behaviour: English is the first column, Hungarian is the second
![image](https://github.com/user-attachments/assets/65640bfb-53c3-4d4d-8174-1152d4c086ee)

And this happens with some files, it just switch the 2 column.
![image](https://github.com/user-attachments/assets/6112916f-8c1b-4f57-aadd-2a59d025434e)

We use v1.23.3, already tried to delete/re-add files. And this is only happen with 1-2 files from the 15.

**Comment by simonprev** [comment]
Fixed in [v1.23.5](https://github.com/mirego/accent/commit/f20e24db82d96a241c954c63f9ce6496df1af311)
