### ISSUE TITLE
[SUGGESTION] Possibility to format the slug

### ISSUE THREAD

**Issue by quentinlegot** [mirego/accent#450]
Hello,

Nice project, as this would help me centralize all the translation of my project, but I have a blocking point.

One of my project is a minecraft mod and I translate my mod using lang files named `en_us` and `fr_fr` which aren't standardized iso 639-3 codes. 

So I wanted the possibility, for every languages, to format the slug when exporting to local file (and in the opposite way too when syncing).
Per example the formatted slug could be: `%lang%_{lowercase(%lower_region%)}` (with the default region for slug inside accent which doesn't contain region like `US` and `fr`) as opposed to current non-personnalizable format `en-US` and `fr`.

**Comment by simonprev** [comment]
Hello! You can already change the slug in the UI :) 

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/83d9222b-207d-4a16-ac8a-99b952be7dee">

**Comment by quentinlegot** [comment]
> Hello! You can already change the slug in the UI :) 
> 
> <img width="1093" alt="image" src="https://github.com/user-attachments/assets/83d9222b-207d-4a16-ac8a-99b952be7dee">
> 

Thanks you, even knowing it, I took 30 seconds to find the edit button, because it only appears when hovering it, this isn't very accessible when using a phone.

I would suggest to display the button all the time or move all buttons (edit, change to main language and delete language) into a popup or overflow menu that appears when clicking on a 3 dots button 

Thanks you for your quick answer
