### ISSUE TITLE
Can't access documents after page 1 from the dropdown

### ISSUE THREAD

**Issue by ClementChaumel** [mirego/accent#453]
Hi, thanks for maintaining accent !
We ran into a problem today when we couldn't find a document (`preliminary_form` in this case) in the dropdown.
<img width="323" alt="Dropdown" src="https://github.com/user-attachments/assets/8a7609ae-569a-43b8-ae0c-a89baa454b04">

It turns out that we have so many documents that it paginates to 2 pages and as luck would have it, `preliminary_form` is on the second page.
<img width="1088" alt="end of page 1" src="https://github.com/user-attachments/assets/ddc1dd2b-689d-4431-96d7-d83b1a0bc509">

<img width="1159" alt="page 2" src="https://github.com/user-attachments/assets/5c2c3914-3141-422d-9a40-3cd3ca2d2ce9">

It would seem that when populating the dropdown, only the first page is queried. 

I'm happy to help fixing it but would need some pointers.

Cheers! :)

**Comment by simonprev** [comment]
Fixed in [v1.23.5](https://github.com/mirego/accent/commit/f20e24db82d96a241c954c63f9ce6496df1af311) I bump de page size for documents in Strings and Review pages 😄
