### ISSUE TITLE
Large number of issues installing Accent on a freshly-installed Ubuntu 16.04 host

### ISSUE THREAD

**Issue by queer** [mirego/accent#60]
<details>
<summary>Old issue content</summary>
I apologize for the length of this issue, but I didn't want to open up many issues at once, for worry of it being seen as spam or similar. 

Similarly, I apologize for any typos / unclear statements / etc. I would love to be able to file PRs to fix these, but I unfortunately don't have the time for it :(

---

Accent looks interesting, so I wanted to try installing it on a server from DigitalOcean to play with. The default image for droplets (which I used) is a Ubuntu 16.04.5 image, which I feel like would be pretty common.

I tried this exact same process on multiple unique servers - all provisioned with the same image - and every single one of these issues reproduced consistently. 

There are no git tags or GitHub releases for versioning as far as I can tell, so I assumed that just doing a simple "`git clone https://github.com/mirego/accent.git` and go from there" was the correct thing to do. 

---

**Issue 1: `npm --prefix webapp install` fails due to lack of Python 2.7 by default.**

(I'm not sure if this is an issue specific to DigitalOcean's Ubuntu image, or if this is from upstream.)

Accent drags in `node-sass` somewhere in the webapp dependency tree. This ends up using `node-gyp` to compile a bunch of C++, and `node-gyp` wants Python 2.7 installed as `/usr/bin/python`. I ended up solving this by just installing the `python 2.7` package and then manually symlinking it to `/usr/bin/python`. I understand that this is not an issue with Accent per se, but it might be worth including a note for it somewhere as a possible issue.

---

**Issue 2: `build-essential` (or similar package) is required for building both the API and the webapp.**

Both the API and the webapp require a number of development tools (`make`, C compiler, C++ compiler, ...) installed in order to be able to compile. This isn't documented in the README, and may be worth making a note about this. Like the previous one, I understand that this is not an issue with Accent per se, but it might be worth including a note for it somewhere as a possible issue.

---

**Issue 3: Compiling the API from the code on the master branch fails.**

When trying to do `mix ecto.setup`, Mix fails when compiling everything before setting up the database. Specifically, I get this error output:

![absinthe error message](https://i.imgur.com/ygjfAtl.png)

I personally have not done much with Absinthe or GraphQL, so I have no idea what the "correct" solution here is. I ended up solving this by doing `rm -rf ./_build/ && rm -f mix.lock` and then re-fetching/compiling dependencies through Mix. 

---

**Issue 4: Running `mix ecto.setup` is told how to use PostgreSQL with the `DATABASE_URL` environment variable, and this isn't obvious from the README.**

This may have just been a case of me accidentally misunderstanding the README, but in my opinion, configuring `mix ecto.setup` when your database URL isn't `postgres://localhost/accent_development` is non-obvious. 

---

**Issue 5: The API server doesn't have a default port.**

This is probably intentional - in which case feel free to ignore this - but from having used Phoenix in my own projects, I'm used to expecting the port to default to `4000` if none is provided. Simply running `mix phx.server` gave it a port of `nil`, which it obviously doesn't like. This is probably just me misunderstanding something somewhere, but I have no idea what. 

---

**Issue 6: `module :cowboy_router is not available`.**

This one really confused me as to how it was even possible. Phoenix should put cowboy in mix.exs as a dependency by default, but it wasn't there when I was trying to install Accent. As of a4025cd0cf9befea4e66eca51325ac25fa7df5d0, it's still missing from mix.exs: https://github.com/mirego/accent/blob/a4025cd0cf9befea4e66eca51325ac25fa7df5d0/mix.exs#L34-L87

Adding `{:cowboy, "~> 1.0"},` to mix.exs and re-fetching dependencies and recompiling the application fixed it. 

---

**Issue 7: Fully setting up the webapp requires a significant amount of disk space.**

My first attempt at setting up Accent was on a 1 core / 1GB RAM / 20GB disk VPS from DigitalOcean. When trying to do `npm --prefix webapp run start`, it failed due to running out of disk space (I have no idea how; `df -h` showed plenty of free space left on the disk). Using a 2 core / 4GB RAM / 80GB disk server fixed this. 

---

**Issue 8: Not specifying `WEBAPP_PORT` in the environment causes the webapp to bind to port 1.**

That's not a typo; I didn't accidentally forget a few digits or anything. It quite literally binds to port 1 if you fail to specify a port in the `WEBAPP_PORT` environment variable.

![port 1!!!](https://i.imgur.com/jIMVMAM.png)

---

**Issue 9: It isn't obvious that you need to specify `CANONICAL_HOST`/`API_HOST`/`API_WS_HOST` on the webapp and not the API.**

Not specifying any of these environment variables on a non-local installation of the webapp/API causes the webapp to not work correctly. The README says:

https://github.com/mirego/accent/blob/a4025cd0cf9befea4e66eca51325ac25fa7df5d0/README.md#L69

but this this is only true if Accent is running locally! To me, the way the README is written makes it sound like these environment variables should be set *for the API*, when really they need to be set *for the webapp*. 

---

I may have run into more issues beyond this had I kept going; I honestly was struggling to keep myself trying to install it after all this. The basic dev-mode setup worked after all this, but there may have been issues with prod-mode (Google OAuth etc.) that simply didn't show up in dev mode. 

**Please** don't take this as me trying to talk trash about Accent or something like that. I think it's nice software, and I would *really* like to be able to use it for Serious Things(tm), but these installation issues are incredibly frustrating to me as an end-user who doesn't want to just run things on Heroku. 
</details>

**Comment by simonprev** [comment]
Thanks for the detailed issue! I think that the majority of those issues can be resolved by simply adding the missing documentation. The current README should clearly explain a deploy without Heroku and a dev environment wihtout macOS.

There is an issue to have a Docker setup for the project so this could be a step forward in having docs taht works everywhere.

In the meantime, you're free to make a PR that regroup all the difficulties you had in installing Accent, and we can work together in making the README useful 👍

**Comment by queer** [comment]
Hey! I did actually end up making a Docker image myself that helped resolve a majority of these problems for me; it can be found at [queer/docker-accent](https://github.com/queer/docker-accent).

**Comment by fire** [comment]
Hey, I also made a Docker Image that I've hosted in kubernetes. Have a bit of cleanup though.

**Comment by queer** [comment]
Accent seems to work very nicely out-of-the-box with the `mirego/accent` Docker image. Thank you for making Accent! <3
