### ISSUE TITLE
Support Kubernetes statefulset

### ISSUE THREAD

**Issue by fire** [mirego/accent#61]
I may be interested in working on creating a Kubernetes Statefulset deployment of Accent on Google Kubernetes Engine. 

Is there a docker generator?

**Comment by fire** [comment]
Listing of third party docker dependencies:

* postgres/10.5 # Upgrade from 9.6?

Docker creation plan:

* Start with a centos 7 container
* Install:
erlang ~> 20.1
elixir ~> 1.6.0
postgres >= 9.4
node.js >= 8.5.0
libyaml >= 0.1.7
* Install distillery
* Generate distillery package.
* Test kubernetes:
    * postgresql
    * postgresql service
    * accent
    * accent service
    * google account openidc env variable
    * email sending

**Comment by simonprev** [comment]
There are no docker setup for the project but it is a highly requested feature (internally and on this repo). I'll be glad to review a PR that add a basic setup 😄

**Comment by fire** [comment]
See https://github.com/queer/docker-accent, I will look at the kubernetes statefulset.

**Comment by fire** [comment]
Status: Currently unable to set env variables.

Use kubernetes postgres chart

- [x] Start with a debian stetch / elixir 1.6 container
- [x] Install:
- [x] node.js
- [x] libyaml
- [x] Install distillery
- [x] Generate distillery package.
- [ ] Test kubernetes:
    - [x] accent
    - [x] accent service
    - [ ] google account openidc env variable
    - [ ] account restrict domain
    - [ ] postgresql ssl / username password authentication
    - [ ] email sending

**Comment by fire** [comment]
How does one give the google api key at runtime to emberjs?

**Comment by fire** [comment]
One way of making this work is to bake:

* API_HOST
* API_WS_HOST
* CANONICAL_HOST
* GOOGLE_API_CLIENT_ID

into the docker file...

That is an awful method.

**Comment by fire** [comment]
I was able to run the entire app in Kubernetes.

**Comment by simonprev** [comment]
Thank you for your contributions @fire !

~Why do you need to hardcode the env var for the webapp?~ Ah since the EmberJs app is not twelve-factor, you need to provide the environment in the "build release" phase 😢 

I don’t know if this can be fixed…

Your changes for the distillery should probably be in this repo so others could use it. I know the issue has been raised a long time ago: #60 #20

**Comment by fire** [comment]
Regarding the EmberJS env variable hard coding, I thought about uses a search and replaced for hardcoded target values, but that seemed awful too. Thoughts?

**Comment by andreymaznyak** [comment]
> Thank you for your contributions @fire !
> 
> Why do you need to hardcode the env var for the webapp? Ah since the EmberJs app is not twelve-factor, you need to provide the environment in the "build release" phase 😢
> 
> I don’t know if this can be fixed…
> 
> Your changes for the distillery should probably be in this repo so others could use it. I know the issue has been raised a long time ago: #60 #20

Maybe we can add hot env endpoint for some configs and fetch it in runtime.

**Comment by andreymaznyak** [comment]
I want to create helm chart for this project.

**Comment by andreymaznyak** [comment]
@fire please share you statefull-set yml configs.

**Comment by fire** [comment]
I used the wizard for generating a docker image so there is no initial stateful set, but I can copy my config from my running instance.

https://github.com/fire/com-chibifire-deploy/tree/master/kubernetes/18-accent
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "36"
  creationTimestamp: 2018-12-03T11:47:20Z
  generation: 96
  labels:
    app: accent-elixir
  name: accent-elixir
  namespace: default
  resourceVersion: "94039192"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/accent-elixir
  uid: 30f99013-f6f1-11e8-8465-42010a8000ab
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: accent-elixir
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accent-elixir
    spec:
      containers:
      - args:
        - -c
        - /opt/app/bin/start_server migrate && /opt/app/bin/start_server foreground
        command:
        - /bin/sh
        env:
        - name: REPLACE_OS_VARS
          value: "TRUE"
        - name: RESTRICTED_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: RESTRICTED_DOMAIN
              name: accent-elixir-config
        - name: WEBAPP_SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: WEBAPP_SENTRY_DSN
              name: accent-elixir-config
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: SENTRY_DSN
              name: accent-elixir-config
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              key: API_HOST
              name: accent-elixir-config
        - name: API_WS_HOST
          valueFrom:
            configMapKeyRef:
              key: API_WS_HOST
              name: accent-elixir-config
        - name: CANONICAL_HOST
          valueFrom:
            configMapKeyRef:
              key: CANONICAL_HOST
              name: accent-elixir-config
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: accent-elixir-config
        - name: GOOGLE_API_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_API_CLIENT_ID
              name: accent-elixir-config
        - name: MIX_ENV
          valueFrom:
            configMapKeyRef:
              key: MIX_ENV
              name: accent-elixir-config
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: accent-elixir-config
        - name: WEBAPP_EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              key: WEBAPP_EMAIL_HOST
              name: accent-elixir-config
        - name: MAILER_FROM
          valueFrom:
            configMapKeyRef:
              key: MAILER_FROM
              name: accent-elixir-config
        - name: SMTP_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: SMTP_ADDRESS
              name: accent-elixir-config
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              key: SMTP_PORT
              name: accent-elixir-config
        - name: SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SMTP_USERNAME
              name: accent-elixir-config
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SMTP_PASSWORD
              name: accent-elixir-config
        image: ifire/accent:027dd
        imagePullPolicy: IfNotPresent
        name: accent
        ports:
        - containerPort: 4000
          protocol: TCP
        - containerPort: 4200
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  generation: 6
  name: accent
  namespace: default
spec:
  rules:
  - host: accent.apps.example.com
    http:
      paths:
      - backend:
          serviceName: accent
          servicePort: 80
        path: /
  tls:
  - hosts:
    - accent.apps.example.com
secretName: accent-tls
```
Hope that helps.

**Comment by fire** [comment]
Should be fairly trivial to make this a stateful set since the problem is the config variables.

**Comment by fire** [comment]
Reminder that some of the configuration variables are hard coded...

* API_HOST
* API_WS_HOST
* CANONICAL_HOST
* GOOGLE_API_CLIENT_ID

**Comment by fire** [comment]
ConfigMap

I don't think the config map variables do anything below.

* API_HOST
* API_WS_HOST
* CANONICAL_HOST
* GOOGLE_API_CLIENT_ID

```
apiVersion: v1
data:
  API_HOST: https://accent.apps.example.com
  API_WS_HOST: wss://accent.apps.example.com
  CANONICAL_HOST: accent.apps.example.com
  DATABASE_URL: postgres://postgres:password@example.com/accent
  GOOGLE_API_CLIENT_ID: example.com
  MAILER_FROM: noreply@example.com
  MIX_ENV: prod
  PORT: "4000"
  RESTRICTED_DOMAIN: example.com
  SENTRY_DSN: https://12345678@sentry.io/12345678
  SMTP_ADDRESS: smtp.sendgrid.net
  SMTP_PASSWORD: PASSWORDPASSWORD
  SMTP_PORT: "587"
  SMTP_USERNAME: apikey
  WEBAPP_EMAIL_HOST: chibifire.com
  WEBAPP_SENTRY_DSN: https://12345678@sentry.io/12345678
kind: ConfigMap
```

**Comment by simonprev** [comment]
The webapp has since been updated to not contain hardcoded variable. Also, helm chart is now mentioned in the readme: https://github.com/mirego/accent#kubernetes-helm-chart-setup

We don’t use k8s to deploy Accent so if you have any problems, please open a new issue.
