### ISSUE TITLE
No project master languages available

### ISSUE THREAD

**Issue by phildionne** [mirego/accent#69]
On a fresh heroku install, there are no master languages available in the select component upon creation of a new project.

![screen shot 2019-01-21 at 11 37 10](https://user-images.githubusercontent.com/1047845/51487386-2a516c80-1d71-11e9-9fcf-eab887a38c74.png)

The graphql query is fired and returns no data:

```json
{"data":{"languages":{"entries":[],"__typename":"Languages"}}}
```

I would expect languages to be seeded in the database upon the first heroku `release` with `mix ecto.migrate` as defined in the `Procfile`. Any ideas how I could end up in that state, and how to manually seed the missing data?

Thanks!

**Comment by phildionne** [comment]
Also, I couldn't install accent directly with the heroku button, it failed after the build phase without explanation nor logs. To circumvent I checked-out the repo locally and create an app from scratch, then doing a classic git deploy, hence the possible weird state I'm in.

**Comment by louim** [comment]
Hey! 
If you deployed the app manually, you might be missing the migration that runs when deploying with the Heroku button: https://github.com/mirego/accent/blob/6e4a0d9846d91c02b0b8572f59de52ad75e008be/app.json#L15
You would probably need to run that manually via the Heroku console.

**Comment by phildionne** [comment]
Indeed, this works. Thanks!
