### ISSUE TITLE
Dummy login is always shown, with MIX_ENV=prod and valid GOOGLE_API_CLIENT_ID

### ISSUE THREAD

**Issue by samuelnygaard** [mirego/accent#78]
First of all, thanks for this great project! 👍 

When using the latest version (1.0.0) I cannot use Google login with the following environments:
`MIX_ENV=prod`
`GOOGLE_API_CLIENT_ID=xxxxxxxx.apps.googleusercontent.com`

I'm getting the 'Fake authentication' page.

Im suspecting [`ENV.GOOGLE_LOGIN_ENABLED = environment === 'production';`](https://github.com/mirego/accent/blob/master/webapp/config/environment.js#L46) is the problem, because when Im changing the line to this: 
`ENV.GOOGLE_LOGIN_ENABLED = Boolean(process.env.GOOGLE_API_CLIENT_ID);`
It works like charm.

I hope this is helpful for the project.

// Samuel

**Comment by simonprev** [comment]
Thanks for the report, I will have to investigate this. The expected behaviour should be that the fake login is _not_ available in production, whether or not the `GOOGLE_API_CLIENT_ID` is present.

But its not expected to have both `MIX_ENV=prod` and `GOOGLE_API_CLIENT_ID` and have the fake login 🤔

**Comment by samuelnygaard** [comment]
Okay, cool - if you need any elaboration or similar don't hesitate pinging me.

**Comment by simonprev** [comment]
`master` has been updated to use `environment === 'production' || Boolean(process.env.GOOGLE_API_CLIENT_ID)` to show the Google login or not 😄

So it should always show in a "production" build or in dev if the env is present

**Comment by samuelnygaard** [comment]
Thanks also for the XLIFF support - this project is truly awesome.
