### ISSUE TITLE
Empty rows in just in time panel

### ISSUE THREAD

**Issue by LostKobrakai** [mirego/accent#83]
I imagine the Just in Time panel is also meant to add missing translations. Currently when a value is not translated in the target language the shown row is simply empty. I think having the text of the master language shown would be quite good here. Also having some kind of "this is not translated" value would also be benefitial to simply showing anything between the borders.

**Comment by simonprev** [comment]
> Currently when a value is not translated in the target language the shown row is simply empty

When is that the case? When you sync the master language, the default behaviour is to put the master translation on all languages. 

I think that putting a different border color for "not translated string" could be a nice addition 👍

**Comment by LostKobrakai** [comment]
By now I'm still in evaluation mode and I've basically just imported .po files I already had in phoenix.
This is without switching to the JIPT language, but simply by opening the panel and selecting the english language (which is my master).

<img width="528" alt="Screenshot 2019-06-18 09 27 17" src="https://user-images.githubusercontent.com/2489835/59661563-5ef41380-91ab-11e9-8b2c-f0da954fccb2.png">
<img width="453" alt="Screenshot 2019-06-18 09 27 38" src="https://user-images.githubusercontent.com/2489835/59661571-61ef0400-91ab-11e9-92a5-1918d8e523d4.png">

**Comment by simonprev** [comment]
This has been fixed with https://github.com/mirego/accent/commit/47b76423bb334cd393947b0ef9907f13f85d563f 🎉 

![image](https://user-images.githubusercontent.com/464900/63897602-b7be0480-c9c3-11e9-8a75-6eda11d49abc.png)
