### ISSUE TITLE
Difference between sync and add translations

### ISSUE THREAD

**Issue by LostKobrakai** [mirego/accent#88]
There are different buttons, but from the modals poping up it's not really clear what those do differently.

**Comment by simonprev** [comment]
We could add a link to https://www.accent.reviews/guides/glossary.html#sync

After reading the guide on "sync" and "add translations", do you understand the differences? Main takeaway is:

```
This is because adding translations does exactly the same thing as a sync but it doesn’t remove nor add strings.

The typical use case to add translations is to update locally translated languages to Accent to help the translator.
```

I could also add these lines in the UI directly, what do you think?

**Comment by LostKobrakai** [comment]
I'd like to see them directly in the UI. If I want detailed information I'm fine with looking at docs, but basic distinction should be possible without that.

**Comment by simonprev** [comment]
Did the explanation between the 2 operations makes sense? English is not my first language, I just want to make sure that the difference is clear for everyone using Accent.

**Comment by LostKobrakai** [comment]
I'm not natively speaking english as well. What to me is most confusing even reading the docs is that it's talking about "strings" and "references", where it's not clear what the latter actually is and it's not in the glossary as well.

I'd explain it like this: "Sync will update the list of strings in accent, removing ones missing in the file and adding new ones" and "Add translation does merge translations present in the uploaded file for strings existing in accent"

I'm not sure if "string" is actually a good keyword to use here though. It just has way too much meaning from programming.
