### ISSUE TITLE
Do not overlay the site when loading the javascript

### ISSUE THREAD

**Issue by LostKobrakai** [mirego/accent#94]
I'm loading the javascript for inline translation for each request and the black overlay becomes really annoying after a bit.

**Comment by simonprev** [comment]
I will add an option in the initializing script to prevent the overlay from appearing 👍

**Comment by simonprev** [comment]
I just added the option `o` on initialization to hide the `o`verlay.

```
o: boolean; // Hide black screen overlay on script loading, default: false
```

```js
accent('init', {h: 'http://localhost:8001', i: '07f82329-a4c4-43d1-88f8-07a699bf3466', o: true});
```

🎉
