### ISSUE TITLE
New auth system: A few things that could be mentioned in the readme

### ISSUE THREAD

**Issue by louim** [mirego/accent#99]
Hey!

While updating to the latest version, I encountered a few hiccups that could be mentioned in the readme to ease the upgrade process.

- `WEBAPP_AUTH_PROVIDERS` is a required environment variable. If not defined, only the dummy auth will be presented, even if providers are configured correctly:
https://github.com/mirego/accent/blob/55c40bc617eb56df665e872feebe68f633ec8e30/webapp/config/environment.js#L9
- Callback urls are `auth/(slack|github|google)/callback` and should be configured in the provider.
- The frontend app must be rebuilt when changing either of `API_WS_HOST`,`API_HOST`, `WEBAPP_AUTH_PROVIDERS`. When deploying to Heroku, updating/setting the environment variable is not enough.

**Comment by simonprev** [comment]
Hey Louis-Michel, the way to package the Ember app and fetching the providers has been rewritten. It infers the providers from the `GITHUB_CLIENT...` `SLACK_`, etc. No more `WEBAPP_AUTH_PROVIDERS`. And the providers are exposed in the API so no more rebuilding the app on env var changes 🎉
